config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'appointments#index'

    resources :appointments

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :date, :time, presence: true
  belongs_to :client, class_name: "User"

  def start_time
    (self.date.to_s + " " + self.time.to_s).to_datetime
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
    @buttonText = "Make Appointment"
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.client = current_user

    if @appointment.save
      flash[:notice] = "Appointment has been created."
      redirect_to @appointment
    else
      flash.now[:alert] = "Appointment has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
    @buttonText = "Update Appointment"
  end

  def update

    if @appointment.update(appointment_params)
      flash[:notice] = "Appointment has been updated."
      redirect_to @appointment
    else
      flash.now[:alert] = "Appointment has not been updated."
      render "edit"
    end
  end

  def destroy
    @appointment.destroy

    flash[:notice] = "Appointment has been cancelled."
    redirect_to appointments_path
  end

  private
    def appointment_params
      params.require(:appointment).permit(:date, :time)
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The appointment you were looking for could not be found."
      redirect_to appointments_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Appt").join(" - ")
      end
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(appointment) do |f| %>
    <%= f.input :date, html5: true %>
    <%= f.input :time, html5: true %>

  <%= f.button :submit, buttonText, class: "btn-primary" %>
<% end %>

app/views/appointments/edit.html.erb
<header>
  <h3>Edit Appointment</h3>
</header>
<%= render partial:"form", locals: { appointment: @appointment, buttonText: @buttonText } %>

app/views/appointments/index.html.erb
<header>
  <h2>Appointments</h2>
  <% if user_signed_in? %>
    <ul class="actions">
      <li>
        <%= link_to "New Appointment", new_appointment_path, class: "new" %>
      </li>
    </ul>
  <% end %>
</header>

<%= month_calendar events: @appointments do |date, appointments| %>
  <%= date %>

  <% appointments.each do |appointment| %>
    <div>
      <%= link_to "Booking", appointment %>
    </div>
  <% end %>
<% end %>

<div id="appointments">
  <h4>List of bookings</h4>
  <% @appointments.each do |appointment| %>
    <h2><%= link_to appointment.date, appointment %></h2>
  <% end %>
</div>

app/views/appointments/new.html.erb
<header>
  <h3>New Appointment</h3>
</header>
<%= render partial: "form", locals: { appointment: @appointment, buttonText: @buttonText } %>

app/views/appointments/show.html.erb
<header>
  <h3>Appointment Details</h3>
  <% if user_signed_in? && (current_user.admin? || current_user == @appointment.client) %>
    <ul class="actions">
      <li>
        <%= link_to "Edit Appointment", edit_appointment_path(@appointment), class: "edit" %>
      </li>
      <li>
        <%= link_to "Cancel Appointment", appointment_path(@appointment), method: :delete, data: { confirm: "Are you sure you want to cancel this appointment?" }, class: "cancel" %>
      </li>
    </ul>
  <% end %>
</header>

<p>date: <%= @appointment.date %></p>
<p>time: <%= @appointment.time %></p>
<% if @appointment.client %>
  <p>client: <%= @appointment.client.email %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Appt", root_path, class: "navbar-brand" %>
        <button type="button" class="navbar-toggle collaptsed" data-toggle="collapse" data-target="#collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="collapse">
        <ul class="nav navbar-nav">
          <li class="<%= "active" if current_page? ("/") %>">
            <%= link_to "Home", root_path %>
          </li>
          <% unless user_signed_in? %>
            <li class="<%= "active" if current_page? ("/users/sign_up") %>">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="<%= "active" if current_page? ("/users/sign_in") %>">
              <%= link_to "Sign in", new_user_session_path %>
            </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
        <div class="navbar-right">
          <p class="navbar-text">
            Signed in as <%= current_user.email %>
          </p>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">

    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>"><%= message %></div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>